"""empty message

Revision ID: e1075e03a18b
Revises: fe7feeda2d2a
Create Date: 2021-01-10 17:16:41.148441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1075e03a18b'
down_revision = 'fe7feeda2d2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
